Ext.define("asSgis.view.center.StatsInfo", {
	extend: "Ext.window.Window",
	xtype: "asSgis-statsInfo",
	id:"StatsInfo",
	width:1000,
	height:600,
	border:false,
	shadow:false,
	constrain: true,
	title:"통계정보",
	items:[{
		xtype:"container",//전체
		width:1000,
		height:600,
		layout:{
			type:"hbox"
		},
		items:[{
			xtype:"container",//좌
			layout:{
				type:"vbox"
			},
			items:[{
				xtype:"container",//지도이미지
				width:500,
				height:300,
				items:[{
					xtype:"label",
					text:"지도이미지"
				}]
			},{
				xtype:"container",//그리드
				layout:{
					type:"hbox"
				},
				items:[{
					xtype:"container",//그리드1
					width:250,
					items:[{
						xtype:"label",
						cls:"window-title-text",
						text:"전체조사지점"
					},{
						xtype:"grid",
						border:false,
						width:250,
						columns:[{
							text:"구분",
							dataIndex:"flag"
						},{
							text:"결과",
							dataIndex:"result"
						}],
						store:Ext.create("Ext.data.Store",{
							fields:["flag","result"],
							data:[["오염원 지점 수","120개소"],
								  ["검사지점","560"],
								  ["총 검사항목 수","4,250 항목"],
								  ["불검출 조사항목","2,350 항목"]]
						})
					}]
				},{
					xtype:"container",//그리드2
					width:250,
					items:[{
						xtype:"label",
						cls:"window-title-text",
						text:"시설별조사지점"
					},{
						xtype:"grid",
						border:false,
						width:250,
						columns:[{
							text:"구분",
							dataIndex:"flag"
						},{
							text:"결과",
							dataIndex:"result"
						}],
						store:Ext.create("Ext.data.Store",{
							fields:["flag","result"],
							data:[["특정오염토양관리대상시설","84 개소"],
								  ["토양측정망","90개소"],
								  ["토양오염방지 조치명령지역","254 개소"],
								  ["토양실태조사","1,350 항목"]]
						})
					}]
				}]
			}]
		},{
			xtype:"container",//우
			items:[{
				xtype:"label",
				cls:"window-title-text",
				text:"행정구역별 조사지점"
			},{
				xtype:"container",
				height:5
			},{
				xtype:"grid",
				autoScroll:true,
				border:false,
				width:460,
				height:500,
				id:"adminArea",
				columns:[{
					text:"구분",
					dataIndex:"flag"
				},{
					text:"특정오염토양",
					dataIndex:"val01"
				},{
					text:"토양측정망",
					dataIndex:"val02"
				},{
					text:"오염방지조치명령",
					dataIndex:"val03"
				},{
					text:"토양실태조사",
					dataIndex:"val04"
				},{
					text:"합계",
					dataIndex:"sum"
				}],
				store:Ext.create("Ext.data.Store",{
					fields:["flag","val01","val02","val03","val04","sum"],
					data:[["고삼면","5","6","7","8","12"],
						  ["공도읍","5","6","5","8","11"],
						  ["금광면","5","6","2","8","5"],
						  ["대덕면","5","6","1","8","3"],
						  ["미양면","5","6","3","2","7"],
						  ["보개면","5","6","3","2","7"],
						  ["삼죽면","5","6","1","4","2"],
						  ["서운면","5","6","0","1","4"],
						  ["원곡면","5","6","0","8","5"],
						  ["안성1동","5","6","0","1","6"],
						  ["안성2동","5","6","7","4","12"],
						  ["안성3동","5","6","7","8","15"],
						  ["양성면","5","6","0","6","7"],
						  ["일죽면","5","6","0","8","8"],
						  ["죽산면","5","6","0","7","9"]]
				})
			}]
		}]
	}],
	initComponent: function(){
		this.callParent();
	}
});